services:
  redis:
    image: 'redis:7'
    ports:
      - '6379:6379'
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # 🔴 핵심: localhost를 postgres로 덮어쓰기
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      PYTHON_SERVER_URL: ${PYTHON_SERVER_URL}
      JWT_SECRET: ${JWT_SECRET}
